server:
  port: 19092  # 게이트웨이 서비스가 실행될 포트 번호

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: AccountService
          uri: lb://AccountService
          predicates:
            - Path=/api/account-transactions/**, /api/direct-debits/**, /api/accounts/**
        - id: PersonalHistoryService
          uri: lb://PersonalHistoryService
          predicates:
            - Path=/api/personal-histories/**, /api/budgets/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
        - id: NotificationService
          uri: lb://NotificationService
          predicates:
            - Path=/api/notifications/**
        - id: PerformanceService
          uri: lb://PerformanceService
          predicates:
            - Path=/api/performance/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
    bus:
      destination: banking-platform.dev.event.config-event.json
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    health-check:
      enabled: true
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
    lease-renewal-interval-in-seconds: 30  # 기본값은 30초, 서비스 상태 갱신 주기
    lease-expiration-duration-in-seconds: 90  # 기본값은 90초, 서비스 갱신이 없을 때 만료 시간
    health-check-url-path: /actuator/health # 헬스 체크를 통한 정상작동 확인

management:
  endpoints:
    web:
      exposure:
        include: "*, busrefresh"
  endpoint:
    health:
      show-details: always
    env:
      show-values: "ALWAYS"
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


test:
  config-name: gateway13-Server

springdoc:
  swagger-ui:
    path: /swagger  # Swagger UI 접근 경로
    urls:
      - name: AuthService
        url: http://localhost:19093/v3/api-docs
      - name: ProductService
        url: http://localhost:19094/v3/api-docs
      - name: AccountService
        url: http://localhost:19095/v3/api-docs
      - name: PersonalHistoryService
        url: http://localhost:19096/v3/api-docs
    use-root-path: true
